# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59b5af1a863eeaac768fd2f6dfad8758dfbc4f5bf2a3a64c91b7ff67eeedad603d915d83211951331a76bec1380db195e28aec04ae384f8fd5e9b1e1238476ba

test:
  secret_key_base: def16f3c06c283670867f291fb0c6b8eb9b6c6ebf545238cf027d2dbe035ce8a8f02eb15a942e94ea8d1eb31cfe7dbb5f0deec80a19e04821e7bb2d75c62ce98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
